AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/ClassAndModuleChildren:
  Enabled: false